apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6ztn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-6ztn@sha256:e33d964a7fd51b8bcb4655f428a4c02dcbd2202c95a4a347a2484a6f4844d5b9
        name: my-nodejs
        resources: {}
status: {}
